#!/bin/bash

# example_2011: 
# ./ctc-start.sh example_2011_data/output/web

APP="ccmorph-ctc"
OFF='\033[0m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m' 

source env/bin/activate

test_docker=`docker ps > /dev/null`
docker_status=$?
if [ $docker_status -eq 127 ]
then
    echo $test_docker
    echo "Install docker to run click-the-coast app"
    exit
elif [ $docker_status -eq 1 ] 
then
    echo $test_docker
    echo "Start docker service to run click-the-coast app"
    exit
fi

if [ ! -d "$1" ]
then
    echo "The first argument should be the path to the data directory for the web application generated by shaper-py (e.g.: ./docker.sh example_2011_data/output/web) "
    exit
fi

docker image inspect "$APP" >/dev/null 2>&1
if [ $? -ne 0 ]
then
    echo -e "$YELLOW---> Build the docker $APP image $OFF"
    echo -e "FROM php:7.2-apache \nCOPY click-the-coast-js/ /var/www/html/" > Dockerfile
    docker build . -t "$APP" # build image
    rm -f Dockerfile
fi

echo -e "$YELLOW---> Run $APP container $OFF"
docker run -d --name "$APP" -p 8082:80 "$APP" # create/run container
docker exec -t "$APP" sh -c "chown -R www-data:www-data *" # change app files owner

echo -e "$YELLOW---> Copy data to $APP container $OFF"
docker exec -t "$APP" sh -c "rm -rf data/*"
docker cp "$1" "$APP":/var/www/html/data/
docker exec -t "$APP" sh -c "chown -R www-data:www-data *" # change app files owner

echo -e "\nTo run Click-The-Coast app open: $GREEN http://localhost:8082 $OFF"
echo -e "When you have finished with the Click-The-Coast application, call the ctc-download.sh script to copy the data from the application to a local directory (e.g. ./ctc-download.sh example_2011_data/output/web/results/). Once copied, you can run the analysis again (e.g. ./example_2011.sh --analyse)."
